# Documentation about Django forms: 
# https://docs.djangoproject.com/en/4.1/topics/forms/
#
# Form fields:
# https://docs.djangoproject.com/en/4.1/ref/forms/fields/
#
# Widgets:
# https://docs.djangoproject.com/en/4.1/ref/forms/widgets/
#
# Range slider:
# https://www.w3schools.com/howto/howto_js_rangeslider.asp

from django import forms

class VoterForm(forms.Form):
    choices = [(-1.0, "Strongly Oppose"), (-0.5, "Oppose"), (0.0, "Mixed/No Opinion"), (0.5, "Support"), (1.0, "Strongly Support")]
    weight_choices = [(0.1, "Very Irrelevant"), (0.25, "Somewhat Irrelevant"), (0.5, "Neither Important nor Irrelevant"), (0.75, "Somewhat Important"), (1.0, "Very Important")]

    Abortion = forms.ChoiceField(label='Abortion', choices=choices, initial=0.0)
    Abortion_weight = forms.ChoiceField(label='Abortion weight', choices=weight_choices, initial=0.5)
    Planned_Parenthood_Funding = forms.ChoiceField(label='Planned Parenthood Funding', choices=choices, initial=0.0)
    Planned_Parenthood_Funding_weight = forms.ChoiceField(label='Planned Parenthood Funding weight', choices=weight_choices, initial=0.5)
    Cut_Government_Spending = forms.ChoiceField(label='Cut Government Spending', choices=choices, initial=0.0)
    Cut_Government_Spending_weight = forms.ChoiceField(label='Cut Government Spending weight', choices=weight_choices, initial=0.5)
    Gay_Marriage = forms.ChoiceField(label='Gay Marriage', choices=choices, initial=0.0)
    Gay_Marriage_weight = forms.ChoiceField(label='Gay Marriage weight', choices=weight_choices, initial=0.5)
    Gender_Identity = forms.ChoiceField(label='Gender Identity', choices=choices, initial=0.0)
    Gender_Identity_weight = forms.ChoiceField(label='Gender Identity weight', choices=weight_choices, initial=0.5)
    Raise_Corporate_Tax = forms.ChoiceField(label='Raise Corporate Tax', choices=choices, initial=0.0)
    Raise_Corporate_Tax_weight = forms.ChoiceField(label='Raise Corporate Tax weight', choices=weight_choices, initial=0.5)
    Social_Media_Regulation = forms.ChoiceField(label='Social Media Regulation', choices=choices, initial=0.0)
    Social_Media_Regulation_weight = forms.ChoiceField(label='Social Media Regulation weight', choices=weight_choices, initial=0.5)
    Death_Penalty = forms.ChoiceField(label='Death Penalty', choices=choices, initial=0.0)
    Death_Penalty_weight = forms.ChoiceField(label='Death Penalty weight', choices=weight_choices, initial=0.5)
    Defund_the_Police = forms.ChoiceField(label='Defund the Police', choices=choices, initial=0.0)
    Defund_the_Police_weight = forms.ChoiceField(label='Defund the Police weight', choices=weight_choices, initial=0.5)
    Mandatory_Minimum_Prison_Sentences = forms.ChoiceField(label='Mandatory Minimum Prison Sentences', choices=choices, initial=0.0)
    Mandatory_Minimum_Prison_Sentences_weight = forms.ChoiceField(label='Mandatory Minimum Prison Sentences weight', choices=weight_choices, initial=0.5)
    Police_Body_Cameras = forms.ChoiceField(label='Police Body Cameras', choices=choices, initial=0.0)
    Police_Body_cameras_weight = forms.ChoiceField(label='Police Body Cameras weight', choices=weight_choices, initial=0.5)
    Qualified_Immunity_for_Police = forms.ChoiceField(label='Qualified Immunity for Police', choices=choices, initial=0.0)
    Qualified_Immunity_for_Police_weight = forms.ChoiceField(label='Qualified Immunity for Police weight', choices=weight_choices, initial=0.5)
    Decriminalizing_Marijuana = forms.ChoiceField(label='Decriminalizing Marijuana', choices=choices, initial=0.0)
    Decriminalizing_Marijuana_weight = forms.ChoiceField(label='Decriminalizing Marijuana weight', choices=weight_choices, initial=0.5)
    Critical_Race_Theory = forms.ChoiceField(label='Critical Race Theory', choices=choices, initial=0.0)
    Critical_Race_Theory_weight = forms.ChoiceField(label='Critical Race Theory weight', choices=weight_choices, initial=0.5)
    Free_College_for_All = forms.ChoiceField(label='Free College for All', choices=choices, initial=0.0)
    Free_College_for_All_weight = forms.ChoiceField(label='Free College for All weight', choices=weight_choices, initial=0.5)
    School_Choice = forms.ChoiceField(label='School Choice', choices=choices, initial=0.0)
    School_Choice_weight = forms.ChoiceField(label='School Choice weight', choices=weight_choices, initial=0.5)
    Student_Loan_Forgiveness = forms.ChoiceField(label='Student Loan Forgiveness', choices=choices, initial=0.0)
    Student_Loan_Forgiveness_weight = forms.ChoiceField(label='Student Loan Forgiveness weight', choices=weight_choices, initial=0.5)
    Universal_Pre_K = forms.ChoiceField(label='Universal Pre-K', choices=choices, initial=0.0)
    Universal_Pre_K_weight = forms.ChoiceField(label='Universal Pre-K weight', choices=weight_choices, initial=0.5)
    Drilling_Allowed_in_Alaskan_Wildlife_Refuge = forms.ChoiceField(label='Drilling Allowed in Alaskan Wildlife Refuge', choices=choices, initial=0.0)
    Drilling_Allowed_in_Alaskan_Wildlife_Refuge_weight = forms.ChoiceField(label='Drilling Allowed in Alaskan Wildlife Refuge weight', choices=weight_choices, initial=0.5)
    Alternative_Energy = forms.ChoiceField(label='Alternative Energy', choices=choices, initial=0.0)
    Alternative_Energy_weight = forms.ChoiceField(label='Alternative Energy weight', choices=weight_choices, initial=0.5)
    Fracking = forms.ChoiceField(label='Fracking', choices=choices, initial=0.0)
    Fracking_weight = forms.ChoiceField(label='Fracking weight', choices=weight_choices, initial=0.5)
    Fighting_Climate_Change = forms.ChoiceField(label='Fighting Climate Change', choices=choices, initial=0.0)
    Fighting_Climate_Change_weight = forms.ChoiceField(label='Fighting Climate Change weight', choices=weight_choices, initial=0.5)
    Increase_Foreign_Aid = forms.ChoiceField(label='Increase Foreign Aid', choices=choices, initial=0.0)
    Increase_Foreign_Aid_weight = forms.ChoiceField(label='Increase Foreign Aid weight', choices=weight_choices, initial=0.5)
    Military_Funding_and_Supplies_for_Ukraine = forms.ChoiceField(label='Military Funding and Supplies for Ukraine', choices=choices, initial=0.0)
    Military_Funding_and_Supplies_for_Ukraine_weight = forms.ChoiceField(label='Military Funding and Supplies for Ukraine weight', choices=weight_choices, initial=0.5)
    NAFTA = forms.ChoiceField(label='NAFTA', choices=choices, initial=0.0)
    NAFTA_weight = forms.ChoiceField(label='NAFTA weight', choices=weight_choices, initial=0.5)
    Increasing_Trade_Tariffs = forms.ChoiceField(label='Increasing Trade Tariffs', choices=choices, initial=0.0)
    Increasing_Trade_Tariffs_weight = forms.ChoiceField(label='Increasing Trade Tariffs weight', choices=weight_choices, initial=0.5)
    Voter_ID_Laws = forms.ChoiceField(label='Voter ID Laws', choices=choices, initial=0.0)
    Voter_ID_Laws_weight = forms.ChoiceField(label='Voter ID Laws weight', choices=weight_choices, initial=0.5)
    Gun_Control = forms.ChoiceField(label='Gun Control', choices=choices, initial=0.0)
    Gun_Control_weight = forms.ChoiceField(label='Gun Control weight', choices=weight_choices, initial=0.5)
    Gun_Liability = forms.ChoiceField(label='Gun Liability', choices=choices, initial=0.0)
    Gun_Liability_weight = forms.ChoiceField(label='Gun Liability weight', choices=weight_choices, initial=0.5)
    Mandatory_Vaccinations = forms.ChoiceField(label='Mandatory Vaccinations', choices=choices, initial=0.0)
    Mandatory_Vaccinations_weight = forms.ChoiceField(label='Mandatory Vaccinations weight', choices=weight_choices, initial=0.5)
    Medicaid = forms.ChoiceField(label='Medicaid', choices=choices, initial=0.0)
    Medicaid_weight = forms.ChoiceField(label='Medicaid weight', choices=weight_choices, initial=0.5)
    Single_Payer_Healthcare = forms.ChoiceField(label='Single-Payer Healthcare', choices=choices, initial=0.0)
    Single_Payer_Healthcare_weight = forms.ChoiceField(label='Single-Payer Healthcare weight', choices=weight_choices, initial=0.5)
    Strengthen_Border_Security = forms.ChoiceField(label='Strengthen Border Security', choices=choices, initial=0.0)
    Strengthen_Border_Security_weight = forms.ChoiceField(label='Strengthen Border Security weight', choices=weight_choices, initial=0.5)
    Illegal_Immigrant_Detainment = forms.ChoiceField(label='Illegal Immigrant Detainment', choices=choices, initial=0.0)
    Illegal_Immigrant_Detainment_weight = forms.ChoiceField(label='Illegal Immigrant Detainment weight', choices=weight_choices, initial=0.5)
    Illegal_Immigrant_Healthcare = forms.ChoiceField(label='Illegal Immigrant Healthcare', choices=choices, initial=0.0)
    Illegal_Immigrant_Healthcare_weight = forms.ChoiceField(label='Illegal Immigrant Healthcare weight', choices=weight_choices, initial=0.5)
    Equal_Pay = forms.ChoiceField(label='Equal Pay', choices=choices, initial=0.0)
    Equal_Pay_weight = forms.ChoiceField(label='Equal Pay weight', choices=weight_choices, initial=0.5)
    Increasing_Minimum_Wage = forms.ChoiceField(label='Increasing Minimum Wage', choices=choices, initial=0.0)
    Increasing_Minimum_Wage_weight = forms.ChoiceField(label='Increasing Minimum Wage weight', choices=weight_choices, initial=0.5)
    Increasing_Welfare_Benefits = forms.ChoiceField(label='Increasing Welfare Benefits', choices=choices, initial=0.0)
    Increasing_Welfare_Benefits_weight = forms.ChoiceField(label='Increasing Welfare Benefits weight', choices=weight_choices, initial=0.5)
    Labor_Unions = forms.ChoiceField(label='Labor Unions', choices=choices, initial=0.0)
    Labor_Unions_weight = forms.ChoiceField(label='Labor Unions weight', choices=weight_choices, initial=0.5)
    Social_Security_Reform = forms.ChoiceField(label='Social Security Reform', choices=choices, initial=0.0)
    Social_Security_Reform_weight = forms.ChoiceField(label='Social Security Reform weight', choices=weight_choices, initial=0.5)
    Capital_Gains_Tax = forms.ChoiceField(label='Capital Gains Tax', choices=choices, initial=0.0)
    Capital_Gains_Tax_weight = forms.ChoiceField(label='Capital Gains Tax weight', choices=weight_choices, initial=0.5)
    Increasing_Taxes_on_Wealthy = forms.ChoiceField(label='Increasing Taxes on Wealthy', choices=choices, initial=0.0)
    Increasing_Taxes_on_Wealthy_weight = forms.ChoiceField(label='Increasing Taxes on Wealthy', choices=weight_choices, initial=0.5)

class CandidateForm(forms.Form):
    choices = [(-1.0, "Opposes"), (0.0, "Mixed/Unkown"), (1.0, "Supports")]

    Abortion = forms.ChoiceField(label='Abortion', choices=choices, initial=0.0)
    Planned_Parenthood_Funding = forms.ChoiceField(label='Planned Parenthood Funding', choices=choices, initial=0.0)
    Cut_Government_Spending = forms.ChoiceField(label='Cut Government Spending', choices=choices, initial=0.0)
    Gay_Marriage = forms.ChoiceField(label='Gay Marriage', choices=choices, initial=0.0)
    Gender_Identity = forms.ChoiceField(label='Gender Identity', choices=choices, initial=0.0)
    Raise_Corporate_Tax = forms.ChoiceField(label='Raise Corporate Tax', choices=choices, initial=0.0)
    Social_Media_Regulation = forms.ChoiceField(label='Social Media Regulation', choices=choices, initial=0.0)
    Death_Penalty = forms.ChoiceField(label='Death Penalty', choices=choices, initial=0.0)
    Defund_the_Police = forms.ChoiceField(label='Defund the Police', choices=choices, initial=0.0)
    Mandatory_Minimum_Prison_Sentences = forms.ChoiceField(label='Mandatory Minimum Prison Sentences', choices=choices, initial=0.0)
    Police_Body_Cameras = forms.ChoiceField(label='Police Body Cameras', choices=choices, initial=0.0)
    Qualified_Immunity_for_Police = forms.ChoiceField(label='Qualified Immunity for Police', choices=choices, initial=0.0)
    Decriminalizing_Marijuana = forms.ChoiceField(label='Decriminalizing Marijuana', choices=choices, initial=0.0)
    Critical_Race_Theory = forms.ChoiceField(label='Critical Race Theory', choices=choices, initial=0.0)
    Free_College_for_All = forms.ChoiceField(label='Free College for All', choices=choices, initial=0.0)
    School_Choice = forms.ChoiceField(label='School Choice', choices=choices, initial=0.0)
    Student_Loan_Forgiveness = forms.ChoiceField(label='Student Loan Forgiveness', choices=choices, initial=0.0)
    Universal_Pre_K = forms.ChoiceField(label='Universal Pre-K', choices=choices, initial=0.0)
    Drilling_Allowed_in_Alaskan_Wildlife_Refuge = forms.ChoiceField(label='Drilling Allowed in Alaskan Wildlife Refuge', choices=choices, initial=0.0)
    Alternative_Energy = forms.ChoiceField(label='Alternative Energy', choices=choices, initial=0.0)
    Fracking = forms.ChoiceField(label='Fracking', choices=choices, initial=0.0)
    Fighting_Climate_Change = forms.ChoiceField(label='Fighting Climate Change', choices=choices, initial=0.0)
    Increase_Foreign_Aid = forms.ChoiceField(label='Increase Foreign Aid', choices=choices, initial=0.0)
    Military_Funding_and_Supplies_for_Ukraine = forms.ChoiceField(label='Military Funding and Supplies for Ukraine', choices=choices, initial=0.0)
    NAFTA = forms.ChoiceField(label='NAFTA', choices=choices, initial=0.0)
    Increasing_Trade_Tariffs = forms.ChoiceField(label='Increasing Trade Tariffs', choices=choices, initial=0.0)
    Voter_ID_Laws = forms.ChoiceField(label='Voter ID Laws', choices=choices, initial=0.0)
    Gun_Control = forms.ChoiceField(label='Gun Control', choices=choices, initial=0.0)
    Gun_Liability = forms.ChoiceField(label='Gun Liability', choices=choices, initial=0.0)
    Mandatory_Vaccinations = forms.ChoiceField(label='Mandatory Vaccinations', choices=choices, initial=0.0)
    Medicaid = forms.ChoiceField(label='Medicaid', choices=choices, initial=0.0)
    Single_Payer_Healthcare = forms.ChoiceField(label='Single-Payer Healthcare', choices=choices, initial=0.0)
    Strengthen_Border_Security = forms.ChoiceField(label='Strengthen Border Security', choices=choices, initial=0.0)
    Illegal_Immigrant_Detainment = forms.ChoiceField(label='Illegal Immigrant Detainment', choices=choices, initial=0.0)
    Illegal_Immigrant_Healthcare = forms.ChoiceField(label='Illegal Immigrant Healthcare', choices=choices, initial=0.0)
    Equal_Pay = forms.ChoiceField(label='Equal Pay', choices=choices, initial=0.0)
    Increasing_Minimum_Wage = forms.ChoiceField(label='Increasing Minimum Wage', choices=choices, initial=0.0)
    Increasing_Welfare_Benefits = forms.ChoiceField(label='Increasing Welfare Benefits', choices=choices, initial=0.0)
    Labor_Unions = forms.ChoiceField(label='Labor Unions', choices=choices, initial=0.0)
    Social_Security_Reform = forms.ChoiceField(label='Social Security Reform', choices=choices, initial=0.0)
    Capital_Gains_Tax = forms.ChoiceField(label='Capital Gains Tax', choices=choices, initial=0.0)
    Increasing_Taxes_on_Wealthy = forms.ChoiceField(label='Increasing Taxes on Wealthy', choices=choices, initial=0.0)
