# Generated by Django 3.2.17 on 2023-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_useropinion_voteropinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='voteropinion',
            name='position',
            field=models.FloatField(),
        ),
    ]
