# Generated by Django 4.1.7 on 2023-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_voter_score_candidatescore_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
