# Generated by Django 3.2.17 on 2023-02-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230227_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteropinion',
            old_name='user',
            new_name='voter',
        ),
    ]
