# Generated by Django 4.0.2 on 2023-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_voteropinion_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteropinion',
            name='position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='voteropinion',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
