# Generated by Django 3.2.17 on 2023-03-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_voteropinion_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat'), ('I', 'Independent')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='voteropinion',
            name='position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='voteropinion',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
