# Generated by Django 4.0.4 on 2023-03-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_voteropinion_position_and_more'),
        ('core', '0008_auto_20230305_0030'),
    ]

    operations = [
    ]
